name: ecuaphotos-market-ci

on:
  push:
    branches:
      - '**'

  pull_request:
    branches:
      - '**'

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python 3.8.x
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          npm install

      - name: Lint with ESlint
        run: |
          npm run lint

      - name: Test with jest
        run: |
          npm run test
